CREATE DATABASE IF NOT EXISTS todo_db;

USE todo_db;

CREATE TABLE tasks (
	id INT(10) NOT NULL AUTO_INCREMENT,
    task VARCHAR(100) NOT NULL,
    isComplete BOOL DEFAULT 0,
    timeCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);